export function handleError(e: Error): void {
  console.log(e);
}
